# permissions for end users to edit gitpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitpod-editor-role
rules:
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods/status
  verbs:
  - get
